project:
  type: website

website:
  title: "Crónicas de Micelio"
  navbar:

     right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css

